language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - make test

after_success:
  - codecov

notifications:
  email: false
  slack: gimme-gimme-gimme:uY4HHVgymLh2iLILqZahaOPK
